package com.cem.pojo;
// default package

// Generated 2017-4-8 15:47:26 by Hibernate Tools 4.3.1.Final

/**
 * Alumniassociation generated by hbm2java
 */
public class AlumniAssociation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1620299566301181001L;
	private Integer alumniAssociationId;
	private String alumniAssociationName;
	private String contactPerson;
	private String contactWay;
	private String img;
	private Integer width;
	private Integer height;
	private String isDeleted;

	public AlumniAssociation() {
	}

	public AlumniAssociation(String alumniAssociationName, String contactPerson, String contactWay, String isDeleted) {
		this.alumniAssociationName = alumniAssociationName;
		this.contactPerson = contactPerson;
		this.contactWay = contactWay;
		this.isDeleted = isDeleted;
	}

	public AlumniAssociation(String alumniAssociationName, String contactPerson, String contactWay, String img,
			String isDeleted) {
		this.alumniAssociationName = alumniAssociationName;
		this.contactPerson = contactPerson;
		this.contactWay = contactWay;
		this.img = img;
		this.isDeleted = isDeleted;
	}

	public AlumniAssociation(String alumniAssociationName, String contactPerson, String contactWay, String img,
			Integer width, Integer height, String isDeleted) {
		this.alumniAssociationName = alumniAssociationName;
		this.contactPerson = contactPerson;
		this.contactWay = contactWay;
		this.img = img;
		this.isDeleted = isDeleted;
		this.width = width;
		this.height = height;
	}

	
	
	public Integer getWidth() {
		return width;
	}

	public void setWidth(Integer width) {
		this.width = width;
	}

	public Integer getHeight() {
		return height;
	}

	public void setHeight(Integer height) {
		this.height = height;
	}

	public Integer getAlumniAssociationId() {
		return this.alumniAssociationId;
	}

	public void setAlumniAssociationId(Integer alumniAssociationId) {
		this.alumniAssociationId = alumniAssociationId;
	}

	public String getAlumniAssociationName() {
		return this.alumniAssociationName;
	}

	public void setAlumniAssociationName(String alumniAssociationName) {
		this.alumniAssociationName = alumniAssociationName;
	}

	public String getContactPerson() {
		return this.contactPerson;
	}

	public void setContactPerson(String contactPerson) {
		this.contactPerson = contactPerson;
	}

	public String getContactWay() {
		return this.contactWay;
	}

	public void setContactWay(String contactWay) {
		this.contactWay = contactWay;
	}

	public String getImg() {
		return this.img;
	}

	public void setImg(String img) {
		this.img = img;
	}

	public String getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(String isDeleted) {
		this.isDeleted = isDeleted;
	}

}
