package com.cem.pojo;
// Generated 2017-2-24 22:31:30 by Hibernate Tools 4.0.1.Final

/**
 * Bbsrank generated by hbm2java
 */
public class Bbsrank implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6898625417583991533L;
	private String rankId;
	private String rankName;
	private String icon;
	private char isDeleted;

	public Bbsrank() {
	}

	public Bbsrank(String rankId, char isDeleted) {
		this.rankId = rankId;
		this.isDeleted = isDeleted;
	}

	public Bbsrank(String rankId, String rankName, String icon, char isDeleted) {
		this.rankId = rankId;
		this.rankName = rankName;
		this.icon = icon;
		this.isDeleted = isDeleted;
	}

	public String getRankId() {
		return this.rankId;
	}

	public void setRankId(String rankId) {
		this.rankId = rankId;
	}

	public String getRankName() {
		return this.rankName;
	}

	public void setRankName(String rankName) {
		this.rankName = rankName;
	}

	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	public char getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(char isDeleted) {
		this.isDeleted = isDeleted;
	}

}
