package com.cem.pojo;
// Generated 2017-3-6 17:24:33 by Hibernate Tools 4.0.1.Final

/**
 * Collegeevent generated by hbm2java
 */
public class Collegeevent implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3265426074339201714L;
	private Integer eventId;
	private String eventTitle;
	private String eventDetail;
	private String eventImg;
	private String eventDate;
	private Integer width;
	private Integer height;
	private String isDeleted;

	public Collegeevent() {
	}

	public Collegeevent(String eventTitle, String eventDetail, String eventDate, String isDeleted) {
		this.eventTitle = eventTitle;
		this.eventDetail = eventDetail;
		this.eventDate = eventDate;
		this.isDeleted = isDeleted;
	}

	public Collegeevent(String eventTitle, String eventDetail, String eventImg, String eventDate, String isDeleted) {
		this.eventTitle = eventTitle;
		this.eventDetail = eventDetail;
		this.eventImg = eventImg;
		this.eventDate = eventDate;
		this.isDeleted = isDeleted;
	}

	public Integer getEventId() {
		return this.eventId;
	}

	public void setEventId(Integer eventId) {
		this.eventId = eventId;
	}

	public String getEventTitle() {
		return this.eventTitle;
	}

	public void setEventTitle(String eventTitle) {
		this.eventTitle = eventTitle;
	}

	public String getEventDetail() {
		return this.eventDetail;
	}

	public void setEventDetail(String eventDetail) {
		this.eventDetail = eventDetail;
	}

	public String getEventImg() {
		return this.eventImg;
	}

	public void setEventImg(String eventImg) {
		this.eventImg = eventImg;
	}

	public String getEventDate() {
		return this.eventDate;
	}

	public void setEventDate(String eventDate) {
		this.eventDate = eventDate;
	}

	public Integer getWidth() {
		return width;
	}

	public void setWidth(Integer width) {
		this.width = width;
	}

	public Integer getHeight() {
		return height;
	}

	public void setHeight(Integer height) {
		this.height = height;
	}

	public String getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(String isDeleted) {
		this.isDeleted = isDeleted;
	}

}
