package com.cem.pojo;
// Generated 2017-2-24 22:31:30 by Hibernate Tools 4.0.1.Final

/**
 * Degree generated by hbm2java
 */
public class Degree implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2103947972218190449L;
	private String degreeId;
	private String degreeName;
	private String isDeleted;

	public Degree() {
	}

	public Degree(String degreeId, String degreeName, String isDeleted) {
		this.degreeId = degreeId;
		this.degreeName = degreeName;
		this.isDeleted = isDeleted;
	}

	public String getDegreeId() {
		return this.degreeId;
	}

	public void setDegreeId(String degreeId) {
		this.degreeId = degreeId;
	}

	public String getDegreeName() {
		return this.degreeName;
	}

	public void setDegreeName(String degreeName) {
		this.degreeName = degreeName;
	}

	public String getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(String isDeleted) {
		this.isDeleted = isDeleted;
	}

}
