package com.cem.pojo;
// Generated 2017-2-24 22:31:30 by Hibernate Tools 4.0.1.Final

import java.util.Date;

/**
 * Donation generated by hbm2java
 */
public class Donation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4890074618980788312L;
	private int donationId;
	private String truename;
	private Integer userId;
	private String donationProject;
	private String donationType;
	private String donationItem;
	private Date donationDate;
	private String isDeleted;

	public Donation() {
	}

	public Donation(int donationId, String isDeleted) {
		this.donationId = donationId;
		this.isDeleted = isDeleted;
	}

	public Donation(int donationId, String truename, Integer userId, String donationProject, String donationType,
			String donationItem, Date donationDate, String isDeleted) {
		this.donationId = donationId;
		this.truename = truename;
		this.userId = userId;
		this.donationProject = donationProject;
		this.donationType = donationType;
		this.donationItem = donationItem;
		this.donationDate = donationDate;
		this.isDeleted = isDeleted;
	}

	public int getDonationId() {
		return this.donationId;
	}

	public void setDonationId(int donationId) {
		this.donationId = donationId;
	}

	public String getTruename() {
		return this.truename;
	}

	public void setTruename(String truename) {
		this.truename = truename;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getDonationProject() {
		return this.donationProject;
	}

	public void setDonationProject(String donationProject) {
		this.donationProject = donationProject;
	}

	public String getDonationType() {
		return this.donationType;
	}

	public void setDonationType(String donationType) {
		this.donationType = donationType;
	}

	public String getDonationItem() {
		return this.donationItem;
	}

	public void setDonationItem(String donationItem) {
		this.donationItem = donationItem;
	}

	public Date getDonationDate() {
		return this.donationDate;
	}

	public void setDonationDate(Date donationDate) {
		this.donationDate = donationDate;
	}

	public String getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(String isDeleted) {
		this.isDeleted = isDeleted;
	}

}
