package com.cem.pojo;
// Generated 2017-2-24 16:54:12 by Hibernate Tools 4.0.1.Final

import java.util.Date;

/**
 * Donation generated by hbm2java
 */
public class Donation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3123334995972963145L;
	private Long donationId;
	private String truename;
	private Long userId;
	private String donationProject;
	private Character dinationType;
	private Character donationItem;
	private Date donationDate;
	private char isDeleted;

	public Donation() {
	}

	public Donation(char isDeleted) {
		this.isDeleted = isDeleted;
	}

	public Donation(String truename, Long userId, String donationProject, Character dinationType,
			Character donationItem, Date donationDate, char isDeleted) {
		this.truename = truename;
		this.userId = userId;
		this.donationProject = donationProject;
		this.dinationType = dinationType;
		this.donationItem = donationItem;
		this.donationDate = donationDate;
		this.isDeleted = isDeleted;
	}

	public Long getDonationId() {
		return this.donationId;
	}

	public void setDonationId(Long donationId) {
		this.donationId = donationId;
	}

	public String getTruename() {
		return this.truename;
	}

	public void setTruename(String truename) {
		this.truename = truename;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public String getDonationProject() {
		return this.donationProject;
	}

	public void setDonationProject(String donationProject) {
		this.donationProject = donationProject;
	}

	public Character getDinationType() {
		return this.dinationType;
	}

	public void setDinationType(Character dinationType) {
		this.dinationType = dinationType;
	}

	public Character getDonationItem() {
		return this.donationItem;
	}

	public void setDonationItem(Character donationItem) {
		this.donationItem = donationItem;
	}

	public Date getDonationDate() {
		return this.donationDate;
	}

	public void setDonationDate(Date donationDate) {
		this.donationDate = donationDate;
	}

	public char getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(char isDeleted) {
		this.isDeleted = isDeleted;
	}

}
