package com.cem.pojo;
// Generated 2017-2-24 22:31:30 by Hibernate Tools 4.0.1.Final

/**
 * Forum generated by hbm2java
 */
public class Forum implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4696824177219569933L;
	private int forumId;
	private String forumTitle;
	private String forumContent;
	private String forumModule;
	private Integer userId;
	private String username;
	private String truename;
	private String topic;
	private String publishTime;
	private String updateTime;
	private Integer replyCount;
	private Integer viewCount;
	private byte[] attachment;
	private String isFine;
	private String isDeleted;

	public Forum() {
	}

	public Forum(int forumId, String isDeleted) {
		this.forumId = forumId;
		this.isDeleted = isDeleted;
	}

	public Forum(int forumId, String forumTitle, String forumModule, Integer userId, String username, String truename,
			String topic, String publishTime, String updateTime, Integer replyCount, Integer viewCount, byte[] attachment,
			String isFine, String isDeleted) {
		this.forumId = forumId;
		this.forumTitle = forumTitle;
		this.forumModule = forumModule;
		this.userId = userId;
		this.username = username;
		this.truename = truename;
		this.topic = topic;
		this.publishTime = publishTime;
		this.updateTime = updateTime;
		this.replyCount = replyCount;
		this.viewCount = viewCount;
		this.attachment = attachment;
		this.isFine = isFine;
		this.isDeleted = isDeleted;
	}
	

	public String getForumContent() {
		return forumContent;
	}

	public void setForumContent(String forumContent) {
		this.forumContent = forumContent;
	}

	public Forum(int forumId, String forumTitle, String forumContent, String forumModule, Integer userId,
			String username, String truename, String topic, String publishTime, String updateTime, Integer replyCount,
			Integer viewCount, byte[] attachment, String isFine, String isDeleted) {
		super();
		this.forumId = forumId;
		this.forumTitle = forumTitle;
		this.forumContent = forumContent;
		this.forumModule = forumModule;
		this.userId = userId;
		this.username = username;
		this.truename = truename;
		this.topic = topic;
		this.publishTime = publishTime;
		this.updateTime = updateTime;
		this.replyCount = replyCount;
		this.viewCount = viewCount;
		this.attachment = attachment;
		this.isFine = isFine;
		this.isDeleted = isDeleted;
	}

	public int getForumId() {
		return this.forumId;
	}

	public void setForumId(int forumId) {
		this.forumId = forumId;
	}

	public String getForumTitle() {
		return this.forumTitle;
	}

	public void setForumTitle(String forumTitle) {
		this.forumTitle = forumTitle;
	}

	public String getForumModule() {
		return this.forumModule;
	}

	public void setForumModule(String forumModule) {
		this.forumModule = forumModule;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getTruename() {
		return this.truename;
	}

	public void setTruename(String truename) {
		this.truename = truename;
	}

	public String getTopic() {
		return this.topic;
	}

	public void setTopic(String topic) {
		this.topic = topic;
	}

	public String getPublishTime() {
		return this.publishTime;
	}

	public void setPublishTime(String string) {
		this.publishTime = string;
	}

	public String getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(String updateTime) {
		this.updateTime = updateTime;
	}

	public Integer getReplyCount() {
		return this.replyCount;
	}

	public void setReplyCount(Integer replyCount) {
		this.replyCount = replyCount;
	}

	public Integer getViewCount() {
		return this.viewCount;
	}

	public void setViewCount(Integer viewCount) {
		this.viewCount = viewCount;
	}

	public byte[] getAttachment() {
		return this.attachment;
	}

	public void setAttachment(byte[] attachment) {
		this.attachment = attachment;
	}

	public String getIsFine() {
		return this.isFine;
	}

	public void setIsFine(String isFine) {
		this.isFine = isFine;
	}

	public String getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(String isDeleted) {
		this.isDeleted = isDeleted;
	}

}
