package com.cem.pojo;
// Generated 2017-2-24 22:31:30 by Hibernate Tools 4.0.1.Final

/**
 * Majorabilitycultivationquality generated by hbm2java
 */
public class Majorabilitycultivationquality implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3572952522163972283L;
	private int userId;
	private short teacherProfessionalismLevel;
	private short teacherTeachingLevel;
	private short relationshipOfTcherAndStud;
	private short majorCultivationTargetAndSocialFit;
	private short internationalCommunicationLearning;
	private short baseCourseLearning;
	private short majorCourseLearning;
	private short majorExperiment;
	private short majorInternship;
	private short graduationDesign;
	private short textbookUsed;
	private short majorCompetitionActivity;
	private short schoolAcademicLecture;
	private short recreationalActivities;
	private short physicalFitness;
	private short learningAtmosphereConstruction;
	private short libraryEffect;
	private short instructorWorking;
	private short logisticServiceWorking;
	private short fellowConnectionWorking;
	private short careerPlanningAndEmploymentGuidance;
	private short psychologyGrooming;
	private Short tutorGuidance;
	private Short projectExperience;
	private Short scientificResearchOpportunity;
	private Short scienReschSpiritAndAcademicMoral;
	private String isDeleted;

	public Majorabilitycultivationquality() {
	}

	public Majorabilitycultivationquality(int userId, short teacherProfessionalismLevel, short teacherTeachingLevel,
			short relationshipOfTcherAndStud, short majorCultivationTargetAndSocialFit,
			short internationalCommunicationLearning, short baseCourseLearning, short majorCourseLearning,
			short majorExperiment, short majorInternship, short graduationDesign, short textbookUsed,
			short majorCompetitionActivity, short schoolAcademicLecture, short recreationalActivities,
			short physicalFitness, short learningAtmosphereConstruction, short libraryEffect, short instructorWorking,
			short logisticServiceWorking, short fellowConnectionWorking, short careerPlanningAndEmploymentGuidance,
			short psychologyGrooming, String isDeleted) {
		this.userId = userId;
		this.teacherProfessionalismLevel = teacherProfessionalismLevel;
		this.teacherTeachingLevel = teacherTeachingLevel;
		this.relationshipOfTcherAndStud = relationshipOfTcherAndStud;
		this.majorCultivationTargetAndSocialFit = majorCultivationTargetAndSocialFit;
		this.internationalCommunicationLearning = internationalCommunicationLearning;
		this.baseCourseLearning = baseCourseLearning;
		this.majorCourseLearning = majorCourseLearning;
		this.majorExperiment = majorExperiment;
		this.majorInternship = majorInternship;
		this.graduationDesign = graduationDesign;
		this.textbookUsed = textbookUsed;
		this.majorCompetitionActivity = majorCompetitionActivity;
		this.schoolAcademicLecture = schoolAcademicLecture;
		this.recreationalActivities = recreationalActivities;
		this.physicalFitness = physicalFitness;
		this.learningAtmosphereConstruction = learningAtmosphereConstruction;
		this.libraryEffect = libraryEffect;
		this.instructorWorking = instructorWorking;
		this.logisticServiceWorking = logisticServiceWorking;
		this.fellowConnectionWorking = fellowConnectionWorking;
		this.careerPlanningAndEmploymentGuidance = careerPlanningAndEmploymentGuidance;
		this.psychologyGrooming = psychologyGrooming;
		this.isDeleted = isDeleted;
	}

	public Majorabilitycultivationquality(int userId, short teacherProfessionalismLevel, short teacherTeachingLevel,
			short relationshipOfTcherAndStud, short majorCultivationTargetAndSocialFit,
			short internationalCommunicationLearning, short baseCourseLearning, short majorCourseLearning,
			short majorExperiment, short majorInternship, short graduationDesign, short textbookUsed,
			short majorCompetitionActivity, short schoolAcademicLecture, short recreationalActivities,
			short physicalFitness, short learningAtmosphereConstruction, short libraryEffect, short instructorWorking,
			short logisticServiceWorking, short fellowConnectionWorking, short careerPlanningAndEmploymentGuidance,
			short psychologyGrooming, Short tutorGuidance, Short projectExperience, Short scientificResearchOpportunity,
			Short scienReschSpiritAndAcademicMoral, String isDeleted) {
		this.userId = userId;
		this.teacherProfessionalismLevel = teacherProfessionalismLevel;
		this.teacherTeachingLevel = teacherTeachingLevel;
		this.relationshipOfTcherAndStud = relationshipOfTcherAndStud;
		this.majorCultivationTargetAndSocialFit = majorCultivationTargetAndSocialFit;
		this.internationalCommunicationLearning = internationalCommunicationLearning;
		this.baseCourseLearning = baseCourseLearning;
		this.majorCourseLearning = majorCourseLearning;
		this.majorExperiment = majorExperiment;
		this.majorInternship = majorInternship;
		this.graduationDesign = graduationDesign;
		this.textbookUsed = textbookUsed;
		this.majorCompetitionActivity = majorCompetitionActivity;
		this.schoolAcademicLecture = schoolAcademicLecture;
		this.recreationalActivities = recreationalActivities;
		this.physicalFitness = physicalFitness;
		this.learningAtmosphereConstruction = learningAtmosphereConstruction;
		this.libraryEffect = libraryEffect;
		this.instructorWorking = instructorWorking;
		this.logisticServiceWorking = logisticServiceWorking;
		this.fellowConnectionWorking = fellowConnectionWorking;
		this.careerPlanningAndEmploymentGuidance = careerPlanningAndEmploymentGuidance;
		this.psychologyGrooming = psychologyGrooming;
		this.tutorGuidance = tutorGuidance;
		this.projectExperience = projectExperience;
		this.scientificResearchOpportunity = scientificResearchOpportunity;
		this.scienReschSpiritAndAcademicMoral = scienReschSpiritAndAcademicMoral;
		this.isDeleted = isDeleted;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public short getTeacherProfessionalismLevel() {
		return this.teacherProfessionalismLevel;
	}

	public void setTeacherProfessionalismLevel(short teacherProfessionalismLevel) {
		this.teacherProfessionalismLevel = teacherProfessionalismLevel;
	}

	public short getTeacherTeachingLevel() {
		return this.teacherTeachingLevel;
	}

	public void setTeacherTeachingLevel(short teacherTeachingLevel) {
		this.teacherTeachingLevel = teacherTeachingLevel;
	}

	public short getRelationshipOfTcherAndStud() {
		return this.relationshipOfTcherAndStud;
	}

	public void setRelationshipOfTcherAndStud(short relationshipOfTcherAndStud) {
		this.relationshipOfTcherAndStud = relationshipOfTcherAndStud;
	}

	public short getMajorCultivationTargetAndSocialFit() {
		return this.majorCultivationTargetAndSocialFit;
	}

	public void setMajorCultivationTargetAndSocialFit(short majorCultivationTargetAndSocialFit) {
		this.majorCultivationTargetAndSocialFit = majorCultivationTargetAndSocialFit;
	}

	public short getInternationalCommunicationLearning() {
		return this.internationalCommunicationLearning;
	}

	public void setInternationalCommunicationLearning(short internationalCommunicationLearning) {
		this.internationalCommunicationLearning = internationalCommunicationLearning;
	}

	public short getBaseCourseLearning() {
		return this.baseCourseLearning;
	}

	public void setBaseCourseLearning(short baseCourseLearning) {
		this.baseCourseLearning = baseCourseLearning;
	}

	public short getMajorCourseLearning() {
		return this.majorCourseLearning;
	}

	public void setMajorCourseLearning(short majorCourseLearning) {
		this.majorCourseLearning = majorCourseLearning;
	}

	public short getMajorExperiment() {
		return this.majorExperiment;
	}

	public void setMajorExperiment(short majorExperiment) {
		this.majorExperiment = majorExperiment;
	}

	public short getMajorInternship() {
		return this.majorInternship;
	}

	public void setMajorInternship(short majorInternship) {
		this.majorInternship = majorInternship;
	}

	public short getGraduationDesign() {
		return this.graduationDesign;
	}

	public void setGraduationDesign(short graduationDesign) {
		this.graduationDesign = graduationDesign;
	}

	public short getTextbookUsed() {
		return this.textbookUsed;
	}

	public void setTextbookUsed(short textbookUsed) {
		this.textbookUsed = textbookUsed;
	}

	public short getMajorCompetitionActivity() {
		return this.majorCompetitionActivity;
	}

	public void setMajorCompetitionActivity(short majorCompetitionActivity) {
		this.majorCompetitionActivity = majorCompetitionActivity;
	}

	public short getSchoolAcademicLecture() {
		return this.schoolAcademicLecture;
	}

	public void setSchoolAcademicLecture(short schoolAcademicLecture) {
		this.schoolAcademicLecture = schoolAcademicLecture;
	}

	public short getRecreationalActivities() {
		return this.recreationalActivities;
	}

	public void setRecreationalActivities(short recreationalActivities) {
		this.recreationalActivities = recreationalActivities;
	}

	public short getPhysicalFitness() {
		return this.physicalFitness;
	}

	public void setPhysicalFitness(short physicalFitness) {
		this.physicalFitness = physicalFitness;
	}

	public short getLearningAtmosphereConstruction() {
		return this.learningAtmosphereConstruction;
	}

	public void setLearningAtmosphereConstruction(short learningAtmosphereConstruction) {
		this.learningAtmosphereConstruction = learningAtmosphereConstruction;
	}

	public short getLibraryEffect() {
		return this.libraryEffect;
	}

	public void setLibraryEffect(short libraryEffect) {
		this.libraryEffect = libraryEffect;
	}

	public short getInstructorWorking() {
		return this.instructorWorking;
	}

	public void setInstructorWorking(short instructorWorking) {
		this.instructorWorking = instructorWorking;
	}

	public short getLogisticServiceWorking() {
		return this.logisticServiceWorking;
	}

	public void setLogisticServiceWorking(short logisticServiceWorking) {
		this.logisticServiceWorking = logisticServiceWorking;
	}

	public short getFellowConnectionWorking() {
		return this.fellowConnectionWorking;
	}

	public void setFellowConnectionWorking(short fellowConnectionWorking) {
		this.fellowConnectionWorking = fellowConnectionWorking;
	}

	public short getCareerPlanningAndEmploymentGuidance() {
		return this.careerPlanningAndEmploymentGuidance;
	}

	public void setCareerPlanningAndEmploymentGuidance(short careerPlanningAndEmploymentGuidance) {
		this.careerPlanningAndEmploymentGuidance = careerPlanningAndEmploymentGuidance;
	}

	public short getPsychologyGrooming() {
		return this.psychologyGrooming;
	}

	public void setPsychologyGrooming(short psychologyGrooming) {
		this.psychologyGrooming = psychologyGrooming;
	}

	public Short getTutorGuidance() {
		return this.tutorGuidance;
	}

	public void setTutorGuidance(Short tutorGuidance) {
		this.tutorGuidance = tutorGuidance;
	}

	public Short getProjectExperience() {
		return this.projectExperience;
	}

	public void setProjectExperience(Short projectExperience) {
		this.projectExperience = projectExperience;
	}

	public Short getScientificResearchOpportunity() {
		return this.scientificResearchOpportunity;
	}

	public void setScientificResearchOpportunity(Short scientificResearchOpportunity) {
		this.scientificResearchOpportunity = scientificResearchOpportunity;
	}

	public Short getScienReschSpiritAndAcademicMoral() {
		return this.scienReschSpiritAndAcademicMoral;
	}

	public void setScienReschSpiritAndAcademicMoral(Short scienReschSpiritAndAcademicMoral) {
		this.scienReschSpiritAndAcademicMoral = scienReschSpiritAndAcademicMoral;
	}

	public String getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(String isDeleted) {
		this.isDeleted = isDeleted;
	}

}
