package com.cem.pojo;
// Generated 2017-2-24 22:31:30 by Hibernate Tools 4.0.1.Final

/**
 * Recruitment generated by hbm2java
 */
public class Recruitment implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5003886676987050433L;
	private int recruitmentId;
	private String userId;
	private String truename;
	private String publishDate;
	private String companyName;
	private String summary;
	private String connectWay;
	private String attachmentPath;
	private String isDeleted;

	public Recruitment() {
	}

	public Recruitment(int recruitmentId) {
		this.recruitmentId = recruitmentId;
	}

	public Recruitment(int recruitmentId, String userId, String truename, String publishDate, String companyName,
			String summary, String connectWay, String attachmentPath, String isDeleted) {
		this.recruitmentId = recruitmentId;
		this.userId = userId;
		this.truename = truename;
		this.publishDate = publishDate;
		this.companyName = companyName;
		this.summary = summary;
		this.connectWay = connectWay;
		this.attachmentPath = attachmentPath;
		this.isDeleted = isDeleted;
	}

	public int getRecruitmentId() {
		return this.recruitmentId;
	}

	public void setRecruitmentId(int recruitmentId) {
		this.recruitmentId = recruitmentId;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getTruename() {
		return this.truename;
	}

	public void setTruename(String truename) {
		this.truename = truename;
	}

	public String getPublishDate() {
		return this.publishDate;
	}

	public void setPublishDate(String publishDate) {
		this.publishDate = publishDate;
	}

	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	public String getConnectWay() {
		return this.connectWay;
	}

	public void setConnectWay(String connectWay) {
		this.connectWay = connectWay;
	}

	public String getAttachmentPath() {
		return this.attachmentPath;
	}

	public void setAttachmentPath(String attachmentPath) {
		this.attachmentPath = attachmentPath;
	}

	public String getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(String isDeleted) {
		this.isDeleted = isDeleted;
	}

}
