package com.cem.pojo;
// Generated 2017-2-24 22:31:30 by Hibernate Tools 4.0.1.Final

import java.util.Date;

/**
 * Reply generated by hbm2java
 */
public class Reply implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5650533817350174380L;
	private int replyId;
	private String replyText;
	private Integer publishUserId;
	private String publishUser;
	private String forum;
	private Short floor;
	private Date replyTime;
	private String parentReplyId;
	private String replyObject;
	private char isDeleted;

	public Reply() {
	}

	public Reply(int replyId, char isDeleted) {
		this.replyId = replyId;
		this.isDeleted = isDeleted;
	}

	public Reply(int replyId, String replyText, Integer publishUserId, String publishUser, String forum, Short floor,
			Date replyTime, String parentReplyId, String replyObject, char isDeleted) {
		this.replyId = replyId;
		this.replyText = replyText;
		this.publishUserId = publishUserId;
		this.publishUser = publishUser;
		this.forum = forum;
		this.floor = floor;
		this.replyTime = replyTime;
		this.parentReplyId = parentReplyId;
		this.replyObject = replyObject;
		this.isDeleted = isDeleted;
	}

	public int getReplyId() {
		return this.replyId;
	}

	public void setReplyId(int replyId) {
		this.replyId = replyId;
	}

	public String getReplyText() {
		return this.replyText;
	}

	public void setReplyText(String replyText) {
		this.replyText = replyText;
	}

	public Integer getPublishUserId() {
		return this.publishUserId;
	}

	public void setPublishUserId(Integer publishUserId) {
		this.publishUserId = publishUserId;
	}

	public String getPublishUser() {
		return this.publishUser;
	}

	public void setPublishUser(String publishUser) {
		this.publishUser = publishUser;
	}

	public String getForum() {
		return this.forum;
	}

	public void setForum(String forum) {
		this.forum = forum;
	}

	public Short getFloor() {
		return this.floor;
	}

	public void setFloor(Short floor) {
		this.floor = floor;
	}

	public Date getReplyTime() {
		return this.replyTime;
	}

	public void setReplyTime(Date replyTime) {
		this.replyTime = replyTime;
	}

	public String getParentReplyId() {
		return this.parentReplyId;
	}

	public void setParentReplyId(String parentReplyId) {
		this.parentReplyId = parentReplyId;
	}

	public String getReplyObject() {
		return this.replyObject;
	}

	public void setReplyObject(String replyObject) {
		this.replyObject = replyObject;
	}

	public char getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(char isDeleted) {
		this.isDeleted = isDeleted;
	}

}
