package com.cem.pojo;
// Generated 2017-2-24 22:31:30 by Hibernate Tools 4.0.1.Final

/**
 * Schoolexperience generated by hbm2java
 */
public class Schoolexperience implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 711249019701601962L;
	private String schooleExperienceId;
	private String degreeId;
	private String majorId;
	private String isDeleted;

	public Schoolexperience() {
	}

	public Schoolexperience(String schooleExperienceId, String degreeId, String majorId, String isDeleted) {
		this.schooleExperienceId = schooleExperienceId;
		this.degreeId = degreeId;
		this.majorId = majorId;
		this.isDeleted = isDeleted;
	}

	public String getSchooleExperienceId() {
		return this.schooleExperienceId;
	}

	public void setSchooleExperienceId(String schooleExperienceId) {
		this.schooleExperienceId = schooleExperienceId;
	}

	public String getDegreeId() {
		return this.degreeId;
	}

	public void setDegreeId(String degreeId) {
		this.degreeId = degreeId;
	}

	public String getMajorId() {
		return this.majorId;
	}

	public void setMajorId(String majorId) {
		this.majorId = majorId;
	}

	public String getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(String isDeleted) {
		this.isDeleted = isDeleted;
	}

}
