package com.cem.pojo;
// Generated 2017-2-24 22:31:30 by Hibernate Tools 4.0.1.Final

/**
 * Selfabilityquality generated by hbm2java
 */
public class Selfabilityquality implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3128727492678030585L;
	private int userId;
	private short gumptionAndAchvConscious;
	private short companyCooperation;
	private short professionalism;
	private short majorBaseKnowledge;
	private short knowledgeWidth;
	private short foreignLanguage;
	private short acquireAndApplyKnowledge;
	private short selfDealProblem;
	private short practiceAndHandsOn;
	private short motivationAbility;
	private short communicationAndOrganizeAbility;
	private short wordsExpression;
	private short psychologyBearAndAntiFrustration;
	private String isDeleted;

	public Selfabilityquality() {
	}

	public Selfabilityquality(int userId, short gumptionAndAchvConscious, short companyCooperation,
			short professionalism, short majorBaseKnowledge, short knowledgeWidth, short foreignLanguage,
			short acquireAndApplyKnowledge, short selfDealProblem, short practiceAndHandsOn, short motivationAbility,
			short communicationAndOrganizeAbility, short wordsExpression, short psychologyBearAndAntiFrustration,
			String isDeleted) {
		this.userId = userId;
		this.gumptionAndAchvConscious = gumptionAndAchvConscious;
		this.companyCooperation = companyCooperation;
		this.professionalism = professionalism;
		this.majorBaseKnowledge = majorBaseKnowledge;
		this.knowledgeWidth = knowledgeWidth;
		this.foreignLanguage = foreignLanguage;
		this.acquireAndApplyKnowledge = acquireAndApplyKnowledge;
		this.selfDealProblem = selfDealProblem;
		this.practiceAndHandsOn = practiceAndHandsOn;
		this.motivationAbility = motivationAbility;
		this.communicationAndOrganizeAbility = communicationAndOrganizeAbility;
		this.wordsExpression = wordsExpression;
		this.psychologyBearAndAntiFrustration = psychologyBearAndAntiFrustration;
		this.isDeleted = isDeleted;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public short getGumptionAndAchvConscious() {
		return this.gumptionAndAchvConscious;
	}

	public void setGumptionAndAchvConscious(short gumptionAndAchvConscious) {
		this.gumptionAndAchvConscious = gumptionAndAchvConscious;
	}

	public short getCompanyCooperation() {
		return this.companyCooperation;
	}

	public void setCompanyCooperation(short companyCooperation) {
		this.companyCooperation = companyCooperation;
	}

	public short getProfessionalism() {
		return this.professionalism;
	}

	public void setProfessionalism(short professionalism) {
		this.professionalism = professionalism;
	}

	public short getMajorBaseKnowledge() {
		return this.majorBaseKnowledge;
	}

	public void setMajorBaseKnowledge(short majorBaseKnowledge) {
		this.majorBaseKnowledge = majorBaseKnowledge;
	}

	public short getKnowledgeWidth() {
		return this.knowledgeWidth;
	}

	public void setKnowledgeWidth(short knowledgeWidth) {
		this.knowledgeWidth = knowledgeWidth;
	}

	public short getForeignLanguage() {
		return this.foreignLanguage;
	}

	public void setForeignLanguage(short foreignLanguage) {
		this.foreignLanguage = foreignLanguage;
	}

	public short getAcquireAndApplyKnowledge() {
		return this.acquireAndApplyKnowledge;
	}

	public void setAcquireAndApplyKnowledge(short acquireAndApplyKnowledge) {
		this.acquireAndApplyKnowledge = acquireAndApplyKnowledge;
	}

	public short getSelfDealProblem() {
		return this.selfDealProblem;
	}

	public void setSelfDealProblem(short selfDealProblem) {
		this.selfDealProblem = selfDealProblem;
	}

	public short getPracticeAndHandsOn() {
		return this.practiceAndHandsOn;
	}

	public void setPracticeAndHandsOn(short practiceAndHandsOn) {
		this.practiceAndHandsOn = practiceAndHandsOn;
	}

	public short getMotivationAbility() {
		return this.motivationAbility;
	}

	public void setMotivationAbility(short motivationAbility) {
		this.motivationAbility = motivationAbility;
	}

	public short getCommunicationAndOrganizeAbility() {
		return this.communicationAndOrganizeAbility;
	}

	public void setCommunicationAndOrganizeAbility(short communicationAndOrganizeAbility) {
		this.communicationAndOrganizeAbility = communicationAndOrganizeAbility;
	}

	public short getWordsExpression() {
		return this.wordsExpression;
	}

	public void setWordsExpression(short wordsExpression) {
		this.wordsExpression = wordsExpression;
	}

	public short getPsychologyBearAndAntiFrustration() {
		return this.psychologyBearAndAntiFrustration;
	}

	public void setPsychologyBearAndAntiFrustration(short psychologyBearAndAntiFrustration) {
		this.psychologyBearAndAntiFrustration = psychologyBearAndAntiFrustration;
	}

	public String getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(String isDeleted) {
		this.isDeleted = isDeleted;
	}

}
