package com.cem.pojo;
// Generated 2017-2-24 22:31:30 by Hibernate Tools 4.0.1.Final

/**
 * Topic generated by hbm2java
 */
public class Topic implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4187769195255121143L;
	private String topicId;
	private String topicName;
	private String description;
	private String sequence;
	private char isDeleted;

	public Topic() {
	}

	public Topic(String topicId, char isDeleted) {
		this.topicId = topicId;
		this.isDeleted = isDeleted;
	}

	public Topic(String topicId, String topicName, String description, String sequence, char isDeleted) {
		this.topicId = topicId;
		this.topicName = topicName;
		this.description = description;
		this.sequence = sequence;
		this.isDeleted = isDeleted;
	}

	public String getTopicId() {
		return this.topicId;
	}

	public void setTopicId(String topicId) {
		this.topicId = topicId;
	}

	public String getTopicName() {
		return this.topicName;
	}

	public void setTopicName(String topicName) {
		this.topicName = topicName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getSequence() {
		return this.sequence;
	}

	public void setSequence(String sequence) {
		this.sequence = sequence;
	}

	public char getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(char isDeleted) {
		this.isDeleted = isDeleted;
	}

}
